server:
  port: 8080
  servlet:
    context-path: /xsports

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xsports
    username: root
    password: abc123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "_ftgRSsFLkBSA49hhlmZDxAEjXnNMOjfQY18zapMpZyLAc5PTDZu2QSgjMktYpqBe"
  valid-duration: 10
  refreshable-duration: 24
 
file:
  upload-dir: uploads