server:
  port: 8080
  servlet:
    context-path: /xsports

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xsports
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "_ftgRSsFLkBSA49hhlmZDxAEjXnNMOjfQY18zapMpZyLAc5PTDZu2QSgjMktYpqBe"
  valid-duration: 10
  refreshable-duration: 24

cloudinary:
  cloud-name: "dlw2xyay8"
  api-key: "476555591589246"
  api-secret: "CLjF43GAPvQgE-E8nLm9f4tN0lQ"

vnpay:
  tmn-code: DEMOV210
  hash-secret: YOUR_SECRET_KEY
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/payment/vnpay-return
